use master
go
create database BDGestaoSala
go
use BDGestaoSala 
create table SALA (
SALID INT IDENTITY (1,1) PRIMARY KEY,
SALDESCRICAO VARCHAR (50) NOT NULL
) 
GO 
create table OCUPACAO(
  OCUID INT IDENTITY (1,1) PRIMARY KEY,
  SALID INT NOT NULL,
  OCUDATA DATETIME NOT NULL, 
  OCUHORARIOINICIO DATETIME NOT NULL,
  OCUHORAFIM DATETIME NULL
  CONSTRAINT FK_SALAOCUPACAO FOREIGN KEY (SALID)
  REFERENCES SALA(SALID)
 )